### ISSUE TITLE
Hang with high CPU usage when source not available

### ISSUE THREAD

**Issue by benderdave** [sumup-oss/gocat#7]
go version: go1.16.7 linux/amd64
os: linux 5.11.0-31-generic

In tcp-to-unix mode, trying to connect to a missing source causes 100% CPU usage. If the source later becomes available nothing changes.

Example: If no process is listening on port 8999, running..

```
gocat --tcp-to-unix --src 127.0.0.1:8999 --dst /tmp/foo.sock
```

Causes 100% CPU load. Starting a server on 8999 afterwards, say..

```
python3 -m http.server 8999
```
does not cause relaying to connect. On the other hand, if the server is started before gocat, everything works fine.

This is because healthCheckSource in abstract_duplex_relay.go closes the passed listener when it gets an error dialing the source connection. In the Relay function, errors on listener.Accept are ignored (except a context error), so execution spins forever in a loop getting errors on the closed listener.

Will post a PR fix that's been working for me, if that's acceptable.

**Comment by syndbg** [comment]
Nice catch and fix, this totally went past me.

P.S I just saw this months late :open_mouth:
